# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PyProj\Projects\PersonalProjects\P9-Converter\converter.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 210)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.pressTab = QtWidgets.QWidget()
        self.pressTab.setObjectName("pressTab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.pressTab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.pressTab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pconvInput = QtWidgets.QLineEdit(self.pressTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pconvInput.sizePolicy().hasHeightForWidth())
        self.pconvInput.setSizePolicy(sizePolicy)
        self.pconvInput.setMinimumSize(QtCore.QSize(200, 0))
        self.pconvInput.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pconvInput.setText("")
        self.pconvInput.setMaxLength(30)
        self.pconvInput.setObjectName("pconvInput")
        self.horizontalLayout.addWidget(self.pconvInput)
        self.pconvFrom = QtWidgets.QComboBox(self.pressTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pconvFrom.sizePolicy().hasHeightForWidth())
        self.pconvFrom.setSizePolicy(sizePolicy)
        self.pconvFrom.setMinimumSize(QtCore.QSize(60, 0))
        self.pconvFrom.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pconvFrom.setObjectName("pconvFrom")
        self.pconvFrom.addItem("")
        self.pconvFrom.addItem("")
        self.pconvFrom.addItem("")
        self.pconvFrom.addItem("")
        self.pconvFrom.addItem("")
        self.pconvFrom.addItem("")
        self.pconvFrom.addItem("")
        self.horizontalLayout.addWidget(self.pconvFrom)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.pressTab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pconvOutput = QtWidgets.QLabel(self.pressTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pconvOutput.sizePolicy().hasHeightForWidth())
        self.pconvOutput.setSizePolicy(sizePolicy)
        self.pconvOutput.setMinimumSize(QtCore.QSize(0, 0))
        self.pconvOutput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pconvOutput.setObjectName("pconvOutput")
        self.horizontalLayout_3.addWidget(self.pconvOutput)
        self.pconvTo = QtWidgets.QComboBox(self.pressTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pconvTo.sizePolicy().hasHeightForWidth())
        self.pconvTo.setSizePolicy(sizePolicy)
        self.pconvTo.setMinimumSize(QtCore.QSize(60, 0))
        self.pconvTo.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pconvTo.setObjectName("pconvTo")
        self.pconvTo.addItem("")
        self.pconvTo.addItem("")
        self.pconvTo.addItem("")
        self.pconvTo.addItem("")
        self.pconvTo.addItem("")
        self.pconvTo.addItem("")
        self.pconvTo.addItem("")
        self.horizontalLayout_3.addWidget(self.pconvTo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.pcalcBtn = QtWidgets.QPushButton(self.pressTab)
        self.pcalcBtn.setObjectName("pcalcBtn")
        self.horizontalLayout_5.addWidget(self.pcalcBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.tabWidget.addTab(self.pressTab, "")
        self.lenTab = QtWidgets.QWidget()
        self.lenTab.setObjectName("lenTab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.lenTab)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.lenTab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lconvInput = QtWidgets.QLineEdit(self.lenTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lconvInput.sizePolicy().hasHeightForWidth())
        self.lconvInput.setSizePolicy(sizePolicy)
        self.lconvInput.setMinimumSize(QtCore.QSize(200, 0))
        self.lconvInput.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lconvInput.setText("")
        self.lconvInput.setMaxLength(30)
        self.lconvInput.setObjectName("lconvInput")
        self.horizontalLayout_2.addWidget(self.lconvInput)
        self.lconvFrom = QtWidgets.QComboBox(self.lenTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lconvFrom.sizePolicy().hasHeightForWidth())
        self.lconvFrom.setSizePolicy(sizePolicy)
        self.lconvFrom.setMinimumSize(QtCore.QSize(60, 0))
        self.lconvFrom.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lconvFrom.setObjectName("lconvFrom")
        self.lconvFrom.addItem("")
        self.lconvFrom.addItem("")
        self.lconvFrom.addItem("")
        self.lconvFrom.addItem("")
        self.lconvFrom.addItem("")
        self.lconvFrom.addItem("")
        self.lconvFrom.addItem("")
        self.lconvFrom.addItem("")
        self.lconvFrom.addItem("")
        self.lconvFrom.addItem("")
        self.horizontalLayout_2.addWidget(self.lconvFrom)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        spacerItem10 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.lenTab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lconvOutput = QtWidgets.QLabel(self.lenTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lconvOutput.sizePolicy().hasHeightForWidth())
        self.lconvOutput.setSizePolicy(sizePolicy)
        self.lconvOutput.setMinimumSize(QtCore.QSize(0, 0))
        self.lconvOutput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lconvOutput.setObjectName("lconvOutput")
        self.horizontalLayout_8.addWidget(self.lconvOutput)
        self.lconvTo = QtWidgets.QComboBox(self.lenTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lconvTo.sizePolicy().hasHeightForWidth())
        self.lconvTo.setSizePolicy(sizePolicy)
        self.lconvTo.setMinimumSize(QtCore.QSize(60, 0))
        self.lconvTo.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lconvTo.setObjectName("lconvTo")
        self.lconvTo.addItem("")
        self.lconvTo.addItem("")
        self.lconvTo.addItem("")
        self.lconvTo.addItem("")
        self.lconvTo.addItem("")
        self.lconvTo.addItem("")
        self.lconvTo.addItem("")
        self.lconvTo.addItem("")
        self.lconvTo.addItem("")
        self.lconvTo.addItem("")
        self.horizontalLayout_8.addWidget(self.lconvTo)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem11 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.lcalcBtn = QtWidgets.QPushButton(self.lenTab)
        self.lcalcBtn.setObjectName("lcalcBtn")
        self.horizontalLayout_9.addWidget(self.lcalcBtn)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem15)
        self.tabWidget.addTab(self.lenTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pconvInput.setValidator(QDoubleValidator(999999, -999999, 8))

        self.pcalcBtn.clicked.connect(self.calcP)      

    def calcP(self):
        begUnit = self.pconvFrom.currentText()
        finUnit = self.pconvTo.currentText()

        if begUnit == finUnit:
            self.pconvOutput.setText(self.pconvInput.text())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Konwertuj z:"))
        self.pconvInput.setPlaceholderText(_translate("MainWindow", "1"))
        self.pconvFrom.setItemText(0, _translate("MainWindow", "GPa"))
        self.pconvFrom.setItemText(1, _translate("MainWindow", "MPa"))
        self.pconvFrom.setItemText(2, _translate("MainWindow", "kPa"))
        self.pconvFrom.setItemText(3, _translate("MainWindow", "hPa"))
        self.pconvFrom.setItemText(4, _translate("MainWindow", "Pa"))
        self.pconvFrom.setItemText(5, _translate("MainWindow", "mBar"))
        self.pconvFrom.setItemText(6, _translate("MainWindow", "atm"))
        self.label.setText(_translate("MainWindow", "Na:"))
        self.pconvOutput.setText(_translate("MainWindow", "1"))
        self.pconvTo.setItemText(0, _translate("MainWindow", "GPa"))
        self.pconvTo.setItemText(1, _translate("MainWindow", "MPa"))
        self.pconvTo.setItemText(2, _translate("MainWindow", "kPa"))
        self.pconvTo.setItemText(3, _translate("MainWindow", "hPa"))
        self.pconvTo.setItemText(4, _translate("MainWindow", "Pa"))
        self.pconvTo.setItemText(5, _translate("MainWindow", "mBar"))
        self.pconvTo.setItemText(6, _translate("MainWindow", "atm"))
        self.pcalcBtn.setText(_translate("MainWindow", "Oblicz"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pressTab), _translate("MainWindow", "Ciśnienie"))
        self.label_4.setText(_translate("MainWindow", "Konwertuj z:"))
        self.lconvInput.setPlaceholderText(_translate("MainWindow", "1"))
        self.lconvFrom.setItemText(0, _translate("MainWindow", "km"))
        self.lconvFrom.setItemText(1, _translate("MainWindow", "m"))
        self.lconvFrom.setItemText(2, _translate("MainWindow", "dm"))
        self.lconvFrom.setItemText(3, _translate("MainWindow", "cm"))
        self.lconvFrom.setItemText(4, _translate("MainWindow", "mm"))
        self.lconvFrom.setItemText(5, _translate("MainWindow", "in"))
        self.lconvFrom.setItemText(6, _translate("MainWindow", "ft"))
        self.lconvFrom.setItemText(7, _translate("MainWindow", "yd"))
        self.lconvFrom.setItemText(8, _translate("MainWindow", "mi"))
        self.lconvFrom.setItemText(9, _translate("MainWindow", "liga"))
        self.label_2.setText(_translate("MainWindow", "Na:"))
        self.lconvOutput.setText(_translate("MainWindow", "1"))
        self.lconvTo.setItemText(0, _translate("MainWindow", "km"))
        self.lconvTo.setItemText(1, _translate("MainWindow", "m"))
        self.lconvTo.setItemText(2, _translate("MainWindow", "dm"))
        self.lconvTo.setItemText(3, _translate("MainWindow", "cm"))
        self.lconvTo.setItemText(4, _translate("MainWindow", "mm"))
        self.lconvTo.setItemText(5, _translate("MainWindow", "in"))
        self.lconvTo.setItemText(6, _translate("MainWindow", "ft"))
        self.lconvTo.setItemText(7, _translate("MainWindow", "yd"))
        self.lconvTo.setItemText(8, _translate("MainWindow", "mi"))
        self.lconvTo.setItemText(9, _translate("MainWindow", "liga"))
        self.lcalcBtn.setText(_translate("MainWindow", "Oblicz"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lenTab), _translate("MainWindow", "Odległość"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
